const IpcChannels = {
  CONNECT_CLIENT: 'CONNECT_CLIENT',
  INIT_CLIENT: 'INIT_CLIENT',
  DO_PRED: 'DO_PRED',
  DESTORY_CLIENT: 'DESTORY_CLIENT',
  GET_TASK: 'GET_TASK',

  NOTIFY_PROGRESS: 'NOTIFY_PROGRESS',
  NOTIFY_LOAD_CHECKPOINT: 'NOTIFY_LOAD_CHECKPOINT',
  NOTIFY_START_THREAD: 'NOTIFY_START_THREAD',
  NOTIFY_PRED_IMG: 'NOTIFY_PRED_IMG',
  NOTIFY_BATCH_PRED: 'NOTIFY_BATCH_PRED',
  NOTIFY_RESULT: 'NOTIFY_RESULT',
};

module.exports = { IpcChannels };
